# Generated by Django 4.2.1 on 2023-06-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtoken',
            name='token',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
