# Generated by Django 4.2.1 on 2023-06-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registrations', '0003_sentmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentmessage',
            name='message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
