version: '3.8'
services:
  web:
    image: an-wa-bot:v1
    container_name: ask_nithyananda_web
    ports:
      - "8050:8050"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - celery_worker
    volumes:
      - ./app_data:/app/data
    networks:
      - internal

  redis:
    image: redis:6.2
    container_name: redis
    volumes:
      - ./redis_data:/data
    command: ["redis-server", "--bind", "127.0.0.1", "--bind", "0.0.0.0", "--protected-mode", "yes"]
    networks:
      - internal

  celery_worker:
    image: an-wa-bot:v1
    container_name: celery_worker
    command: celery -A scheduler.tasks worker --loglevel=info
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./app_data:/app/data
    networks:
      - internal

networks:
  internal:
    driver: bridge
