version: '3.8'

services:
  web:
    image: an-wa-bot:v1
    container_name: fastapi_web
    ports:
            - "8050:8050"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - celery_worker

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    image: an-wa-bot:v1
    container_name: celery_worker
    command: celery -A scheduler.celery_app worker --loglevel=info
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
