version: '3.8'

services:
  web:
    build: .
    ports:
      - "7262:8000"
    depends_on:
      - redis
    env_file:
      - .env

  celery_worker:
    build: .
    command: celery -A tasks.celery_tasks:app worker --loglevel=info --uid=appuser
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    volumes:
      - ./data/redis_data:/data
    command: redis-server --appendonly yes

  celery_beat:
    build: .
    command: celery -A tasks.celery_tasks:app beat --loglevel=info --uid=appuser
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  redis_data: