version: '3.8'

services:
  web:
    build: .
    ports:
      - "${DOCKER_PORT:-7262}:8000"
    depends_on:
      - redis
    env_file:
      - .env

  celery_worker:
    build: .
    command: celery -A tasks.celery_tasks:app worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env

  celery_beat:
    build: .
    command: celery -A tasks.celery_tasks:app beat --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:s