version: '3.8'
services:
  web:
    build: .
    ports:
      - "7262:8000"
    depends_on:
      - redis
      - db
    environment:
      - SERVICE_NAME=web
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default

  celery_worker:
    build: .
    command: celery -A tasks.celery_tasks.celery_app worker --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      - SERVICE_NAME=celery_worker
    env_file:
      - .env
    networks:
      - default

  celery_beat:
    build: .
    command: celery -A tasks.celery_tasks.celery_app beat --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      - SERVICE_NAME=celery_beat
    env_file:
      - .env
    networks:
      - default

  redis:
    image: "redis:alpine"
    volumes:
      - ./data/redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - default

  db:
    image: postgres:15-alpine
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - default

networks:
  dify-chandra_default:
    external: true
  default:
    driver: bridge

volumes:
  redis_data:
  postgres_data: