services:
  bot:
    build: .
    ports:
      - "7262:8000"
    depends_on:
      - redis
    environment:
      - SERVICE_NAME=web
      - PYTHONPATH=/app
    env_file:
      - .env
    volumes:
      - app_data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default

  celery_worker:
    build: .
    command: celery -A app.worker.celery_app worker --loglevel=info
    depends_on:
      - redis
    environment:
      - SERVICE_NAME=celery_worker
      - PYTHONPATH=/app
      - C_FORCE_ROOT=true
    env_file:
      - .env
    volumes:
      - app_data:/app/data
    networks:
      - default

  celery_beat:
    build: .
    command: celery -A app.worker.celery_app beat --loglevel=info
    depends_on:
      - redis
    environment:
      - SERVICE_NAME=celery_beat
      - PYTHONPATH=/app
      - C_FORCE_ROOT=true
    env_file:
      - .env
    volumes:
      - app_data:/app/data
    networks:
      - default

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  redis_data:
  app_data: