version: '3.8'

services:
  web:
    build: .
    ports:
      - "7262:8000"
    depends_on:
      - redis
      - db
    environment:
      - SERVICE_NAME=web
    env_file:
      - .env

  celery_worker:
    build: .
    command: celery -A tasks.celery_tasks.celery_app worker --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      - SERVICE_NAME=celery_worker
    env_file:
      - .env

  celery_beat:
    build: .
    command: celery -A tasks.celery_tasks.celery_app beat --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      - SERVICE_NAME=celery_beat
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  db:
    image: postgres:15-alpine
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  redis_data:
  postgres_data: