# Generated by Django 4.2.2 on 2024-05-04 08:16

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_historicalepassportnumber_epassportnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 4, 4, 16, 3, 815259), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaluserprofile',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 4, 4, 16, 17, 744322), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
