# Generated by Django 4.2.2 on 2024-05-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_historicaluserprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['updated_at'], name='userprofile_updated_eaaf97_idx'),
        ),
    ]
