# Generated by Django 4.2.2 on 2024-07-14 20:45

from django.db import migrations
import userprofiles.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0004_userprofile_userprofile_updated_eaaf97_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='intention',
            field=userprofiles.fields.IntentionField(choices=[('N', 'None'), ('S', 'Sanyas/Monk'), ('G', 'Gruhastha')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='intention',
            field=userprofiles.fields.IntentionField(choices=[('N', 'None'), ('S', 'Sanyas/Monk'), ('G', 'Gruhastha')], default=None, max_length=1, null=True),
        ),
    ]
