# Generated by Django 5.0.7 on 2024-07-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0006_userprofilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='phone_number_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number_verified',
            field=models.BooleanField(default=False),
        ),
    ]
